#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

topic="${1:-01-what-is-cf/}"

if ! [ -d "$topic" ]
then
  echo "Topic $topic dir does not exist"
  exit 1
fi

cd live || exit 1

trap '{ rm -fr slides.md images; }' EXIT

ln -fs "../${topic}slides.md" ./slides.md
! [ -d "../${topic}images" ] || ln -fs "../${topic}images" ./images
grunt serve
